//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class Abstract___VARIABLE_interactorClassName___: ___VARIABLE_interactorSubclassName___ {}

// MARK: - Interface

extension Abstract___VARIABLE_interactorClassName___: Abstract___VARIABLE_interactorInterfaceName___ {}
