//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_viewClassName___: UIViewController {

    // MARK: - Members

    // swiftlint:disable:next implicitly_unwrapped_optional
    var presenter: ___VARIABLE_moduleName___.PresenterInterface!

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
}
