//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class Abstract___VARIABLE_viewClassName___: UIViewController {

    // MARK: - Members

    // swiftlint:disable:next implicitly_unwrapped_optional
    var underlying___VARIABLE_presenterClassName___: Abstract___VARIABLE_moduleName___.PresenterInterface! {
        didSet {
            _abstract___VARIABLE_moduleName___Presenter = underlying___VARIABLE_presenterClassName___
        }
    }

    // swiftlint:disable:next implicitly_unwrapped_optional
    private(set) var _abstract___VARIABLE_presenterClassName___: Abstract___VARIABLE_moduleName___.PresenterInterface!

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        _abstract___VARIABLE_presenterClassName___.viewDidLoad()
    }
}

// MARK: - Interface

extension Abstract___VARIABLE_viewClassName___: Abstract___VARIABLE_viewInterfaceName___ {}
