//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Wireframe

protocol ___VARIABLE_wireframeInterfaceName___: WireframeInterface {

    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption)
}

// MARK: - View

protocol ___VARIABLE_viewInterfaceName___: ViewInterface {}

// MARK: - Presenter

protocol ___VARIABLE_presenterConfigInterfaceName___: AnyObject {
    // Use this protocol to declare properties used to transfer data between modules in the Wireframe completion
}

protocol ___VARIABLE_presenterInterfaceName___: PresenterInterface {}

@objc
protocol ___VARIABLE_presenterObjcInterfaceName___: AnyObject {}

// MARK: - Interactor

protocol ___VARIABLE_interactorInterfaceName___: InteractorInterface {}

// MARK: - ___VARIABLE_moduleName___

enum ___VARIABLE_moduleName___ {
    typealias PresenterInterface = ___VARIABLE_presenterConfigInterfaceName___
        & ___VARIABLE_presenterInterfaceName___
        & ___VARIABLE_presenterObjcInterfaceName___

    enum NavigationOption {}
}
