//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_interactorClassName___ {}

// MARK: - Interface

extension ___VARIABLE_interactorClassName___: ___VARIABLE_interactorInterfaceName___ {}

// MARK: - Helpers

private extension ___VARIABLE_interactorClassName___ {

    private func foo() {
        print("bar")
    }
}
