//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_presenterClassName___: ___VARIABLE_presenterConfigInterfaceName___ {

    // MARK: - Members

    // Properties declared in ___VARIABLE_presenterConfigInterfaceName___ goes here…
    // And ___VARIABLE_presenterClassName___ properties too

    // MARK: - Wireframe properties

    private(set) unowned var view: ___VARIABLE_viewInterfaceName___
    private(set) var interactor: ___VARIABLE_interactorInterfaceName___
    private(set) var wireframe: ___VARIABLE_wireframeInterfaceName___

    // MARK: - Lifecycle

    init(view: ___VARIABLE_viewInterfaceName___,
         interactor: ___VARIABLE_interactorInterfaceName___,
         wireframe: ___VARIABLE_wireframeInterfaceName___) {

        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }

    deinit {
        // Remove observers, invalidate notificationToken, …
    }

    func viewDidLoad() {
        // Do whatever you want…
    }
}

// MARK: - Interfaces

extension ___VARIABLE_presenterClassName___: ___VARIABLE_presenterInterfaceName___ {}

extension ___VARIABLE_presenterClassName___: ___VARIABLE_presenterObjcInterfaceName___ {}

// MARK: - Helpers

private extension ___VARIABLE_moduleName___Presenter {

    private func foo() {
        print("bar")
    }
}
