//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Wireframe

protocol ___VARIABLE_wireframeInterfaceName___: ___VARIABLE_wireframeSubinterfaceName___ {

    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption)
}

// MARK: - View

protocol ___VARIABLE_viewInterfaceName___: ___VARIABLE_viewSubinterfaceName___ {}

// MARK: - Presenter

protocol ___VARIABLE_presenterConfigInterfaceName___: ___VARIABLE_presenterConfigSubinterfaceName___ {
    // Use this protocol to declare properties settable from the Wireframe completion.
}

protocol ___VARIABLE_presenterInterfaceName___: ___VARIABLE_presenterSubinterfaceName___ {}

@objc
protocol ___VARIABLE_presenterObjcInterfaceName___: ___VARIABLE_presenterObjcSubinterfaceName___ {}

// MARK: - Interactor

protocol ___VARIABLE_interactorInterfaceName___: ___VARIABLE_interactorSubinterfaceName___ {}

// MARK: - ___VARIABLE_moduleName___

enum ___VARIABLE_moduleName___ {
    typealias PresenterInterface = ___VARIABLE_presenterConfigInterfaceName___
        & ___VARIABLE_presenterInterfaceName___
        & ___VARIABLE_presenterObjcInterfaceName___

    enum NavigationOption {}
}
