//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_wireframeClassName___: ___VARIABLE_wireframeSubclassName___<___VARIABLE_viewClassName___> {

    // MARK: - Module setup

    init(completion: ((___VARIABLE_presenterConfigInterfaceName___) -> Void)? = nil) {
        let moduleViewController = ___VARIABLE_viewClassName___()
        super.init(viewController: moduleViewController)

        let interactor = ___VARIABLE_interactorClassName___()
        let presenter = ___VARIABLE_presenterClassName___(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self
        )
        moduleViewController.presenter = presenter
        completion?(presenter)
    }
}

// MARK: - Inteface

extension ___VARIABLE_wireframeClassName___: ___VARIABLE_wireframeInterfaceName___ {

    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption) {}
}
