//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class Abstract___VARIABLE_wireframeClassName___: BaseWireframe {}

// MARK: - Interface

extension Abstract___VARIABLE_wireframeClassName___: Abstract___VARIABLE_wireframeInterfaceName___ {

    func navigate(to option: Abstract___VARIABLE_moduleName___.NavigationOption) {}
}
