//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Wireframe

protocol Abstract___VARIABLE_wireframeInterfaceName___: WireframeInterface {

    func navigate(to option: Abstract___VARIABLE_moduleName___.NavigationOption)
}

// MARK: - View

protocol Abstract___VARIABLE_viewInterfaceName___: ViewInterface {}

// MARK: - Presenter

protocol Abstract___VARIABLE_presenterConfigInterfaceName___: AnyObject {
    // Use this protocol to declare properties settable from the Wireframe completion.
}

protocol Abstract___VARIABLE_presenterInterfaceName___: PresenterInterface {}

@objc
protocol Abstract___VARIABLE_presenterObjcInterfaceName___: AnyObject {}

// MARK: - Interactor

protocol Abstract___VARIABLE_interactorInterfaceName___: InteractorInterface {}

// MARK: - Abstract___VARIABLE_moduleName___

enum Abstract___VARIABLE_moduleName___ {
    typealias PresenterInterface = Abstract___VARIABLE_presenterConfigInterfaceName___
        & Abstract___VARIABLE_presenterInterfaceName___
        & Abstract___VARIABLE_presenterObjcInterfaceName___

    enum NavigationOption {}
}
